/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedDrivesRouteImport } from './routes/_authenticated/drives'
import { Route as AuthenticatedExplorerRouteImport } from './routes/_authenticated/explorer'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSharesRouteImport } from './routes/_authenticated/shares'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal/acceptable-use'
import { Route as LegalDataDeletionRouteImport } from './routes/legal/data-deletion'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAutomationsRouteImport } from './routes/_authenticated/admin.automations'
import { Route as AuthenticatedAdminConfigurationsRouteImport } from './routes/_authenticated/admin.configurations'
import { Route as AuthenticatedAdminConnectionsRouteImport } from './routes/_authenticated/admin.connections'
import { Route as AuthenticatedAdminCredentialsRouteImport } from './routes/_authenticated/admin.credentials'
import { Route as AuthenticatedAdminDrivesRouteImport } from './routes/_authenticated/admin.drives'
import { Route as AuthenticatedAdminFlagsRouteImport } from './routes/_authenticated/admin.flags'
import { Route as AuthenticatedAdminHealthRouteImport } from './routes/_authenticated/admin.health'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin.providers'
import { Route as AuthenticatedAdminQueuesRouteImport } from './routes/_authenticated/admin.queues'
import { Route as AuthenticatedAdminSharesRouteImport } from './routes/_authenticated/admin.shares'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiPublicHealthLiveRouteImport } from './routes/api/public/health.live'
import { Route as ApiPublicHealthReadyRouteImport } from './routes/api/public/health.ready'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1/$'
import { Route as ApiPublicV1OpenapiDotjsonRouteImport } from './routes/api/public/v1/openapi[.]json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDrivesRoute = AuthenticatedDrivesRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExplorerRoute = AuthenticatedExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSharesRoute = AuthenticatedSharesRouteImport.update({
  id: '/shares',
  path: '/shares',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/legal/acceptable-use',
  path: '/legal/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDataDeletionRoute = LegalDataDeletionRouteImport.update({
  id: '/legal/data-deletion',
  path: '/legal/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAutomationsRoute =
  AuthenticatedAdminAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfigurationsRoute =
  AuthenticatedAdminConfigurationsRouteImport.update({
    id: '/configurations',
    path: '/configurations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConnectionsRoute =
  AuthenticatedAdminConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCredentialsRoute =
  AuthenticatedAdminCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDrivesRoute =
  AuthenticatedAdminDrivesRouteImport.update({
    id: '/drives',
    path: '/drives',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFlagsRoute = AuthenticatedAdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminHealthRoute =
  AuthenticatedAdminHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQueuesRoute =
  AuthenticatedAdminQueuesRouteImport.update({
    id: '/queues',
    path: '/queues',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSharesRoute =
  AuthenticatedAdminSharesRouteImport.update({
    id: '/shares',
    path: '/shares',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthLiveRoute = ApiPublicHealthLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ApiPublicHealthRoute,
} as any)
const ApiPublicHealthReadyRoute = ApiPublicHealthReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => ApiPublicHealthRoute,
} as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OpenapiDotjsonRoute =
  ApiPublicV1OpenapiDotjsonRouteImport.update({
    id: '/api/public/v1/openapi.json',
    path: '/api/public/v1/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/automations': typeof AuthenticatedAutomationsRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/drives': typeof AuthenticatedDrivesRoute
  '/explorer': typeof AuthenticatedExplorerRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/shares': typeof AuthenticatedSharesRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/data-deletion': typeof LegalDataDeletionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/s/$token': typeof STokenRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/configurations': typeof AuthenticatedAdminConfigurationsRoute
  '/admin/connections': typeof AuthenticatedAdminConnectionsRoute
  '/admin/credentials': typeof AuthenticatedAdminCredentialsRoute
  '/admin/drives': typeof AuthenticatedAdminDrivesRoute
  '/admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/queues': typeof AuthenticatedAdminQueuesRoute
  '/admin/shares': typeof AuthenticatedAdminSharesRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/public/health': typeof ApiPublicHealthRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/health/live': typeof ApiPublicHealthLiveRoute
  '/api/public/health/ready': typeof ApiPublicHealthReadyRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/drives': typeof AuthenticatedDrivesRoute
  '/explorer': typeof AuthenticatedExplorerRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/shares': typeof AuthenticatedSharesRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/data-deletion': typeof LegalDataDeletionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/s/$token': typeof STokenRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/configurations': typeof AuthenticatedAdminConfigurationsRoute
  '/admin/connections': typeof AuthenticatedAdminConnectionsRoute
  '/admin/credentials': typeof AuthenticatedAdminCredentialsRoute
  '/admin/drives': typeof AuthenticatedAdminDrivesRoute
  '/admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/queues': typeof AuthenticatedAdminQueuesRoute
  '/admin/shares': typeof AuthenticatedAdminSharesRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/public/health': typeof ApiPublicHealthRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/health/live': typeof ApiPublicHealthLiveRoute
  '/api/public/health/ready': typeof ApiPublicHealthReadyRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/developer': typeof AuthenticatedDeveloperRoute
  '/_authenticated/drives': typeof AuthenticatedDrivesRoute
  '/_authenticated/explorer': typeof AuthenticatedExplorerRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/shares': typeof AuthenticatedSharesRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/data-deletion': typeof LegalDataDeletionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/s/$token': typeof STokenRoute
  '/_authenticated/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/_authenticated/admin/configurations': typeof AuthenticatedAdminConfigurationsRoute
  '/_authenticated/admin/connections': typeof AuthenticatedAdminConnectionsRoute
  '/_authenticated/admin/credentials': typeof AuthenticatedAdminCredentialsRoute
  '/_authenticated/admin/drives': typeof AuthenticatedAdminDrivesRoute
  '/_authenticated/admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/_authenticated/admin/health': typeof AuthenticatedAdminHealthRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/_authenticated/admin/queues': typeof AuthenticatedAdminQueuesRoute
  '/_authenticated/admin/shares': typeof AuthenticatedAdminSharesRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/public/health': typeof ApiPublicHealthRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/health/live': typeof ApiPublicHealthLiveRoute
  '/api/public/health/ready': typeof ApiPublicHealthReadyRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/admin'
    | '/automations'
    | '/connections'
    | '/dashboard'
    | '/developer'
    | '/drives'
    | '/explorer'
    | '/onboarding'
    | '/settings'
    | '/shares'
    | '/transfers'
    | '/legal/acceptable-use'
    | '/legal/data-deletion'
    | '/legal/privacy'
    | '/legal/terms'
    | '/s/$token'
    | '/admin/automations'
    | '/admin/configurations'
    | '/admin/connections'
    | '/admin/credentials'
    | '/admin/drives'
    | '/admin/flags'
    | '/admin/health'
    | '/admin/logs'
    | '/admin/providers'
    | '/admin/queues'
    | '/admin/shares'
    | '/settings/security'
    | '/api/public/health'
    | '/api/v1/$'
    | '/admin/'
    | '/api/public/health/live'
    | '/api/public/health/ready'
    | '/api/public/v1/$'
    | '/api/public/v1/openapi.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/automations'
    | '/connections'
    | '/dashboard'
    | '/developer'
    | '/drives'
    | '/explorer'
    | '/onboarding'
    | '/settings'
    | '/shares'
    | '/transfers'
    | '/legal/acceptable-use'
    | '/legal/data-deletion'
    | '/legal/privacy'
    | '/legal/terms'
    | '/s/$token'
    | '/admin/automations'
    | '/admin/configurations'
    | '/admin/connections'
    | '/admin/credentials'
    | '/admin/drives'
    | '/admin/flags'
    | '/admin/health'
    | '/admin/logs'
    | '/admin/providers'
    | '/admin/queues'
    | '/admin/shares'
    | '/settings/security'
    | '/api/public/health'
    | '/api/v1/$'
    | '/admin'
    | '/api/public/health/live'
    | '/api/public/health/ready'
    | '/api/public/v1/$'
    | '/api/public/v1/openapi.json'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/admin'
    | '/_authenticated/automations'
    | '/_authenticated/connections'
    | '/_authenticated/dashboard'
    | '/_authenticated/developer'
    | '/_authenticated/drives'
    | '/_authenticated/explorer'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/shares'
    | '/_authenticated/transfers'
    | '/legal/acceptable-use'
    | '/legal/data-deletion'
    | '/legal/privacy'
    | '/legal/terms'
    | '/s/$token'
    | '/_authenticated/admin/automations'
    | '/_authenticated/admin/configurations'
    | '/_authenticated/admin/connections'
    | '/_authenticated/admin/credentials'
    | '/_authenticated/admin/drives'
    | '/_authenticated/admin/flags'
    | '/_authenticated/admin/health'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/providers'
    | '/_authenticated/admin/queues'
    | '/_authenticated/admin/shares'
    | '/_authenticated/settings/security'
    | '/api/public/health'
    | '/api/v1/$'
    | '/_authenticated/admin/'
    | '/api/public/health/live'
    | '/api/public/health/ready'
    | '/api/public/v1/$'
    | '/api/public/v1/openapi.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalDataDeletionRoute: typeof LegalDataDeletionRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  STokenRoute: typeof STokenRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRouteWithChildren
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
  ApiPublicV1OpenapiDotjsonRoute: typeof ApiPublicV1OpenapiDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drives': {
      id: '/_authenticated/drives'
      path: '/drives'
      fullPath: '/drives'
      preLoaderRoute: typeof AuthenticatedDrivesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explorer': {
      id: '/_authenticated/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof AuthenticatedExplorerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shares': {
      id: '/_authenticated/shares'
      path: '/shares'
      fullPath: '/shares'
      preLoaderRoute: typeof AuthenticatedSharesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/data-deletion': {
      id: '/legal/data-deletion'
      path: '/legal/data-deletion'
      fullPath: '/legal/data-deletion'
      preLoaderRoute: typeof LegalDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/automations': {
      id: '/_authenticated/admin/automations'
      path: '/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configurations': {
      id: '/_authenticated/admin/configurations'
      path: '/configurations'
      fullPath: '/admin/configurations'
      preLoaderRoute: typeof AuthenticatedAdminConfigurationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/connections': {
      id: '/_authenticated/admin/connections'
      path: '/connections'
      fullPath: '/admin/connections'
      preLoaderRoute: typeof AuthenticatedAdminConnectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/credentials': {
      id: '/_authenticated/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AuthenticatedAdminCredentialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/drives': {
      id: '/_authenticated/admin/drives'
      path: '/drives'
      fullPath: '/admin/drives'
      preLoaderRoute: typeof AuthenticatedAdminDrivesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/flags': {
      id: '/_authenticated/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AuthenticatedAdminFlagsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/health': {
      id: '/_authenticated/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthenticatedAdminHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/queues': {
      id: '/_authenticated/admin/queues'
      path: '/queues'
      fullPath: '/admin/queues'
      preLoaderRoute: typeof AuthenticatedAdminQueuesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/shares': {
      id: '/_authenticated/admin/shares'
      path: '/shares'
      fullPath: '/admin/shares'
      preLoaderRoute: typeof AuthenticatedAdminSharesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/live': {
      id: '/api/public/health/live'
      path: '/live'
      fullPath: '/api/public/health/live'
      preLoaderRoute: typeof ApiPublicHealthLiveRouteImport
      parentRoute: typeof ApiPublicHealthRoute
    }
    '/api/public/health/ready': {
      id: '/api/public/health/ready'
      path: '/ready'
      fullPath: '/api/public/health/ready'
      preLoaderRoute: typeof ApiPublicHealthReadyRouteImport
      parentRoute: typeof ApiPublicHealthRoute
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi.json': {
      id: '/api/public/v1/openapi.json'
      path: '/api/public/v1/openapi.json'
      fullPath: '/api/public/v1/openapi.json'
      preLoaderRoute: typeof ApiPublicV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAutomationsRoute: typeof AuthenticatedAdminAutomationsRoute
  AuthenticatedAdminConfigurationsRoute: typeof AuthenticatedAdminConfigurationsRoute
  AuthenticatedAdminConnectionsRoute: typeof AuthenticatedAdminConnectionsRoute
  AuthenticatedAdminCredentialsRoute: typeof AuthenticatedAdminCredentialsRoute
  AuthenticatedAdminDrivesRoute: typeof AuthenticatedAdminDrivesRoute
  AuthenticatedAdminFlagsRoute: typeof AuthenticatedAdminFlagsRoute
  AuthenticatedAdminHealthRoute: typeof AuthenticatedAdminHealthRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
  AuthenticatedAdminQueuesRoute: typeof AuthenticatedAdminQueuesRoute
  AuthenticatedAdminSharesRoute: typeof AuthenticatedAdminSharesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAutomationsRoute: AuthenticatedAdminAutomationsRoute,
  AuthenticatedAdminConfigurationsRoute: AuthenticatedAdminConfigurationsRoute,
  AuthenticatedAdminConnectionsRoute: AuthenticatedAdminConnectionsRoute,
  AuthenticatedAdminCredentialsRoute: AuthenticatedAdminCredentialsRoute,
  AuthenticatedAdminDrivesRoute: AuthenticatedAdminDrivesRoute,
  AuthenticatedAdminFlagsRoute: AuthenticatedAdminFlagsRoute,
  AuthenticatedAdminHealthRoute: AuthenticatedAdminHealthRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
  AuthenticatedAdminQueuesRoute: AuthenticatedAdminQueuesRoute,
  AuthenticatedAdminSharesRoute: AuthenticatedAdminSharesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRoute
  AuthenticatedDrivesRoute: typeof AuthenticatedDrivesRoute
  AuthenticatedExplorerRoute: typeof AuthenticatedExplorerRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSharesRoute: typeof AuthenticatedSharesRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRoute,
  AuthenticatedDrivesRoute: AuthenticatedDrivesRoute,
  AuthenticatedExplorerRoute: AuthenticatedExplorerRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSharesRoute: AuthenticatedSharesRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicHealthRouteChildren {
  ApiPublicHealthLiveRoute: typeof ApiPublicHealthLiveRoute
  ApiPublicHealthReadyRoute: typeof ApiPublicHealthReadyRoute
}

const ApiPublicHealthRouteChildren: ApiPublicHealthRouteChildren = {
  ApiPublicHealthLiveRoute: ApiPublicHealthLiveRoute,
  ApiPublicHealthReadyRoute: ApiPublicHealthReadyRoute,
}

const ApiPublicHealthRouteWithChildren = ApiPublicHealthRoute._addFileChildren(
  ApiPublicHealthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalDataDeletionRoute: LegalDataDeletionRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  STokenRoute: STokenRoute,
  ApiPublicHealthRoute: ApiPublicHealthRouteWithChildren,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
  ApiPublicV1OpenapiDotjsonRoute: ApiPublicV1OpenapiDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
